<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <Nullable>disable</Nullable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="2.2.7" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIC Simulator\SIC Simulator.csproj" />
  </ItemGroup>

</Project>
